#![allow(dead_code)]

use std::{
    any::{type_name, Any, TypeId},
    marker::PhantomData,
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc,
    },
};

type ErasedEvent = dyn Any + Send + Sync;
static NEXT_EVENT_MAP_ID: AtomicU64 = AtomicU64::new(1);

pub const COMPONENT_EVENTS_ABI_V1: &str = "agentview.component-events/v1";

/// Mount-scoped typed route token supplied by the Harness.
pub struct EventInput<E> {
    route: Arc<EventRouteDescriptor>,
    marker: PhantomData<fn() -> E>,
}

impl<E> EventInput<E> {
    pub(crate) fn new(generation: u64) -> Self
    where
        E: Send + Sync + 'static,
    {
        Self {
            route: Arc::new(EventRouteDescriptor::root::<E>(EventInputOrigin {
                map_id: EventMapId::fresh(),
                generation,
            })),
            marker: PhantomData,
        }
    }

    pub(crate) fn generation(&self) -> u64 {
        self.route.origin.generation
    }

    pub(crate) fn origin(&self) -> EventInputOrigin {
        self.route.origin
    }

    pub fn select<Selected>(&self, selector: EventSelector<E, Selected>) -> EventInput<Selected>
    where
        E: Send + Sync + 'static,
        Selected: Send + Sync + 'static,
    {
        EventInput {
            route: Arc::new(EventRouteDescriptor::selected(
                Arc::clone(&self.route),
                selector,
            )),
            marker: PhantomData,
        }
    }

    /// Retains the complete route independently of the authoring token.
    pub(crate) fn route_descriptor(&self) -> Arc<EventRouteDescriptor> {
        Arc::clone(&self.route)
    }
}

impl<E> Clone for EventInput<E> {
    fn clone(&self) -> Self {
        Self {
            route: Arc::clone(&self.route),
            marker: PhantomData,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct EventMapId(u64);

impl EventMapId {
    fn fresh() -> Self {
        let value = NEXT_EVENT_MAP_ID
            .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |value| {
                value.checked_add(1)
            })
            .unwrap_or_else(|_| panic!("EventInput map identity space exhausted"));
        Self(value)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) struct EventInputOrigin {
    map_id: EventMapId,
    generation: u64,
}

/// Selector token generated by `#[derive(ComponentEvents)]`.
///
/// Authors normally use framework selectors such as `ProviderEvent::TEXT`;
/// they do not construct selectors manually.
#[doc(hidden)]
pub struct EventSelector<Root, Selected> {
    route_id: &'static str,
    variant_index: u16,
    abi: &'static str,
    project: for<'a> fn(&'a Root) -> Option<&'a Selected>,
}

impl<Root, Selected> EventSelector<Root, Selected> {
    /// Proc-macro ABI for `#[derive(ComponentEvents)]`.
    ///
    /// The route identity and variant index are declarative topology metadata,
    /// not a security boundary. Attempt preflight must reject collisions.
    #[doc(hidden)]
    pub const fn __component_events_v1(
        route_id: &'static str,
        variant_index: u16,
        project: for<'a> fn(&'a Root) -> Option<&'a Selected>,
    ) -> Self {
        Self {
            route_id,
            variant_index,
            abi: COMPONENT_EVENTS_ABI_V1,
            project,
        }
    }

    pub(crate) const fn route_id(&self) -> &'static str {
        self.route_id
    }

    pub(crate) const fn variant_index(&self) -> u16 {
        self.variant_index
    }

    pub(crate) const fn abi(&self) -> &'static str {
        self.abi
    }

    #[allow(clippy::needless_lifetimes)]
    pub(crate) fn project<'event>(&self, event: &'event Root) -> Option<&'event Selected> {
        (self.project)(event)
    }
}

impl<Root, Selected> Copy for EventSelector<Root, Selected> {}

impl<Root, Selected> Clone for EventSelector<Root, Selected> {
    fn clone(&self) -> Self {
        *self
    }
}

trait ErasedEventProjector: Send + Sync {
    fn project<'event>(&self, parent: &'event ErasedEvent) -> Option<&'event ErasedEvent>;
    fn identity(&self) -> usize;
}

struct TypedEventProjector<Parent, Selected> {
    project: for<'event> fn(&'event Parent) -> Option<&'event Selected>,
}

impl<Parent, Selected> ErasedEventProjector for TypedEventProjector<Parent, Selected>
where
    Parent: Send + Sync + 'static,
    Selected: Send + Sync + 'static,
{
    fn project<'event>(&self, parent: &'event ErasedEvent) -> Option<&'event ErasedEvent> {
        let parent = parent
            .downcast_ref::<Parent>()
            .expect("an EventRouteDescriptor validates its parent event type");
        (self.project)(parent).map(|selected| selected as &ErasedEvent)
    }

    fn identity(&self) -> usize {
        self.project as usize
    }
}

/// Immutable, type-erased route retained by the attempt runtime.
///
/// Every selected descriptor owns its projector and retains its parent by
/// `Arc`, so dropping or cloning an `EventInput` never loses route behavior.
pub(crate) struct EventRouteDescriptor {
    parent: Option<Arc<Self>>,
    origin: EventInputOrigin,
    depth: usize,
    event_type_id: TypeId,
    event_type_name: &'static str,
    selector: Option<ErasedSelectorDescriptor>,
}

struct ErasedSelectorDescriptor {
    route_id: &'static str,
    variant_index: u16,
    abi: &'static str,
    parent_type_id: TypeId,
    parent_type_name: &'static str,
    projector: Box<dyn ErasedEventProjector>,
}

impl EventRouteDescriptor {
    fn root<Root>(origin: EventInputOrigin) -> Self
    where
        Root: Send + Sync + 'static,
    {
        Self {
            parent: None,
            origin,
            depth: 0,
            event_type_id: TypeId::of::<Root>(),
            event_type_name: type_name::<Root>(),
            selector: None,
        }
    }

    fn selected<Parent, Selected>(
        parent: Arc<Self>,
        selector: EventSelector<Parent, Selected>,
    ) -> Self
    where
        Parent: Send + Sync + 'static,
        Selected: Send + Sync + 'static,
    {
        debug_assert_eq!(parent.event_type_id, TypeId::of::<Parent>());
        let depth = parent.depth + 1;
        let origin = parent.origin;
        Self {
            parent: Some(parent),
            origin,
            depth,
            event_type_id: TypeId::of::<Selected>(),
            event_type_name: type_name::<Selected>(),
            selector: Some(ErasedSelectorDescriptor {
                route_id: selector.route_id(),
                variant_index: selector.variant_index(),
                abi: selector.abi(),
                parent_type_id: TypeId::of::<Parent>(),
                parent_type_name: type_name::<Parent>(),
                projector: Box::new(TypedEventProjector {
                    project: selector.project,
                }),
            }),
        }
    }

    pub(crate) const fn depth(&self) -> usize {
        self.depth
    }

    pub(crate) const fn origin(&self) -> EventInputOrigin {
        self.origin
    }

    pub(crate) fn selector_identity(&self) -> Option<&'static str> {
        self.selector.as_ref().map(|selector| selector.route_id)
    }

    pub(crate) fn variant_index(&self) -> Option<u16> {
        self.selector
            .as_ref()
            .map(|selector| selector.variant_index)
    }

    pub(crate) fn selector_abi(&self) -> Option<&'static str> {
        self.selector.as_ref().map(|selector| selector.abi)
    }

    pub(crate) fn topology(&self) -> EventRouteTopology {
        let mut selectors = Vec::with_capacity(self.depth);
        self.append_topology(&mut selectors);
        let mut root = self;
        while let Some(parent) = root.parent.as_deref() {
            root = parent;
        }
        EventRouteTopology {
            root_event_type: root.event_type_name,
            selectors: selectors.into_boxed_slice(),
        }
    }

    fn append_topology(&self, output: &mut Vec<EventRouteSegment>) {
        let Some(parent) = self.parent.as_deref() else {
            return;
        };
        parent.append_topology(output);
        let selector = self
            .selector
            .as_ref()
            .expect("only the root EventRouteDescriptor omits a selector");
        output.push(EventRouteSegment {
            parent_event_type: selector.parent_type_name,
            selected_event_type: self.event_type_name,
            selector_identity: selector.route_id,
            variant_index: selector.variant_index,
            selector_abi: selector.abi,
            projector_identity: selector.projector.identity(),
        });
    }

    pub(crate) fn project_root<'event, Root>(
        &self,
        root: &'event Root,
    ) -> Result<Option<&'event ErasedEvent>, EventRouteProjectionFault>
    where
        Root: Send + Sync + 'static,
    {
        let erased = root as &ErasedEvent;
        self.project_erased(erased, type_name::<Root>())
    }

    fn project_erased<'event>(
        &self,
        root: &'event ErasedEvent,
        observed_root: &'static str,
    ) -> Result<Option<&'event ErasedEvent>, EventRouteProjectionFault> {
        let Some(parent) = &self.parent else {
            if root.type_id() != self.event_type_id {
                return Err(EventRouteProjectionFault::RootTypeMismatch {
                    expected: self.event_type_name,
                    observed: observed_root,
                });
            }
            return Ok(Some(root));
        };

        let Some(parent_event) = parent.project_erased(root, observed_root)? else {
            return Ok(None);
        };
        let selector = self
            .selector
            .as_ref()
            .expect("only the root EventRouteDescriptor omits a selector");
        if parent_event.type_id() != selector.parent_type_id {
            return Err(EventRouteProjectionFault::DescriptorTypeMismatch {
                route: selector.route_id,
                expected: selector.parent_type_name,
            });
        }
        let selected = selector.projector.project(parent_event);
        if let Some(selected) = selected {
            if selected.type_id() != self.event_type_id {
                return Err(EventRouteProjectionFault::SelectorOutputTypeMismatch {
                    route: selector.route_id,
                    expected: self.event_type_name,
                });
            }
        }
        Ok(selected)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) struct EventRouteTopology {
    pub(crate) root_event_type: &'static str,
    pub(crate) selectors: Box<[EventRouteSegment]>,
}

impl EventRouteTopology {
    pub(crate) fn has_projector_collision(&self, other: &Self) -> bool {
        self.root_event_type == other.root_event_type
            && self.selectors.len() == other.selectors.len()
            && self
                .selectors
                .iter()
                .zip(&other.selectors)
                .all(|(left, right)| {
                    left.parent_event_type == right.parent_event_type
                        && left.selected_event_type == right.selected_event_type
                        && left.selector_identity == right.selector_identity
                        && left.variant_index == right.variant_index
                        && left.selector_abi == right.selector_abi
                })
            && self != other
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) struct EventRouteSegment {
    pub(crate) parent_event_type: &'static str,
    pub(crate) selected_event_type: &'static str,
    pub(crate) selector_identity: &'static str,
    pub(crate) variant_index: u16,
    pub(crate) selector_abi: &'static str,
    projector_identity: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[allow(clippy::enum_variant_names)]
pub(crate) enum EventRouteProjectionFault {
    #[error("event route expected root `{expected}` but received `{observed}`")]
    RootTypeMismatch {
        expected: &'static str,
        observed: &'static str,
    },
    #[error("event route `{route}` expected parent `{expected}`")]
    DescriptorTypeMismatch {
        route: &'static str,
        expected: &'static str,
    },
    #[error("event selector `{route}` returned a value other than `{expected}`")]
    SelectorOutputTypeMismatch {
        route: &'static str,
        expected: &'static str,
    },
}

#[cfg(test)]
mod tests {
    use std::{any::type_name, sync::Arc};

    use super::{EventInput, EventSelector, COMPONENT_EVENTS_ABI_V1};

    enum RootEvent {
        Text(String),
        Clock(u64),
        Nested(NestedEvent),
    }

    enum NestedEvent {
        Number(u32),
    }

    #[derive(agentview_derive::ComponentEvents)]
    enum DerivedRootEvent {
        Text(String),
        Clock(u64),
    }

    fn select_text(event: &RootEvent) -> Option<&String> {
        match event {
            RootEvent::Text(value) => Some(value),
            RootEvent::Clock(_) | RootEvent::Nested(_) => None,
        }
    }

    fn select_nested(event: &RootEvent) -> Option<&NestedEvent> {
        match event {
            RootEvent::Nested(value) => Some(value),
            RootEvent::Text(_) | RootEvent::Clock(_) => None,
        }
    }

    fn select_number(event: &NestedEvent) -> Option<&u32> {
        match event {
            NestedEvent::Number(value) => Some(value),
        }
    }

    const TEXT: EventSelector<RootEvent, String> =
        EventSelector::__component_events_v1("Text", 0, select_text);
    const NESTED: EventSelector<RootEvent, NestedEvent> =
        EventSelector::__component_events_v1("Nested", 2, select_nested);
    const NUMBER: EventSelector<NestedEvent, u32> =
        EventSelector::__component_events_v1("Number", 0, select_number);

    #[test]
    fn selected_inputs_keep_generation_and_extend_route_path() {
        let root = EventInput::<RootEvent>::new(7);
        let text = root.select(TEXT);
        let cloned = text.clone();
        let foreign_root = EventInput::<RootEvent>::new(7);

        assert_eq!(root.generation(), 7);
        assert_eq!(root.origin(), text.origin());
        assert_eq!(text.origin(), cloned.origin());
        assert_ne!(root.origin(), foreign_root.origin());
        assert_eq!(root.route_descriptor().depth(), 0);
        assert_eq!(text.generation(), 7);
        assert_eq!(text.route_descriptor().depth(), 1);
        assert_eq!(text.route_descriptor().selector_identity(), Some("Text"));
        assert_eq!(text.route_descriptor().variant_index(), Some(0));
        assert_eq!(
            text.route_descriptor().selector_abi(),
            Some("agentview.component-events/v1")
        );
        assert!(Arc::ptr_eq(
            &text.route_descriptor(),
            &cloned.route_descriptor()
        ));
    }

    #[test]
    fn selector_projects_the_matching_payload_by_borrow() {
        let event = RootEvent::Text(String::from("delta"));
        assert_eq!(TEXT.project(&event).map(String::as_str), Some("delta"));
        assert!(TEXT.project(&RootEvent::Clock(0)).is_none());
    }

    #[test]
    fn descriptor_keeps_the_erased_selector_chain_for_attempt_dispatch() {
        let number_route = EventInput::<RootEvent>::new(11)
            .select(NESTED)
            .select(NUMBER)
            .route_descriptor();

        let event = RootEvent::Nested(NestedEvent::Number(42));
        let projected = number_route
            .project_root(&event)
            .unwrap()
            .expect("both selectors match");
        assert_eq!(projected.downcast_ref::<u32>(), Some(&42));

        let topology = number_route.topology();
        assert_eq!(topology.root_event_type, type_name::<RootEvent>());
        assert_eq!(topology.selectors.len(), 2);
        assert_eq!(topology.selectors[0].selector_identity, "Nested");
        assert_eq!(topology.selectors[1].selector_identity, "Number");
        assert_eq!(topology.selectors[1].variant_index, 0);
        assert_eq!(
            topology.selectors[1].parent_event_type,
            type_name::<NestedEvent>()
        );
        assert_eq!(
            topology.selectors[1].selected_event_type,
            type_name::<u32>()
        );
        assert_eq!(topology.selectors[1].selector_abi, COMPONENT_EVENTS_ABI_V1);

        let unmatched = RootEvent::Text(String::from("quiet"));
        assert!(number_route.project_root(&unmatched).unwrap().is_none());
    }

    #[test]
    fn descriptor_rejects_a_foreign_root_event_type() {
        let route = EventInput::<RootEvent>::new(13)
            .select(TEXT)
            .route_descriptor();

        assert!(route.project_root(&String::from("foreign")).is_err());
    }

    #[test]
    fn derived_selector_retains_its_projector_and_abi_in_the_descriptor() {
        fn assert_copy<T: Copy>(_: T) {}
        assert_copy(DerivedRootEvent::TEXT);

        let route = EventInput::<DerivedRootEvent>::new(17)
            .select(DerivedRootEvent::TEXT)
            .route_descriptor();
        let event = DerivedRootEvent::Text(String::from("derived"));

        assert_eq!(route.selector_abi(), Some("agentview.component-events/v1"));
        assert_eq!(
            route
                .project_root(&event)
                .unwrap()
                .and_then(|event| event.downcast_ref::<String>())
                .map(String::as_str),
            Some("derived")
        );
        assert!(route
            .project_root(&DerivedRootEvent::Clock(1))
            .unwrap()
            .is_none());

        let clock_route = EventInput::<DerivedRootEvent>::new(19)
            .select(DerivedRootEvent::CLOCK)
            .route_descriptor();
        let clock_topology = clock_route.topology();
        assert_eq!(clock_topology.selectors[0].variant_index, 1);
        assert!(clock_topology.selectors[0]
            .selector_identity
            .ends_with("::DerivedRootEvent::Clock"));
    }
}
