use std::{
    collections::{hash_map::Entry, HashMap, HashSet, VecDeque},
    fmt,
    future::Future,
    pin::Pin,
    sync::Arc,
};

use crate::{
    component::execution::{ToolCall, ToolDefinition, ToolDefinitionError, ToolOutput},
    transcript::CanonicalInputItem,
};
use schemars::JsonSchema;
use serde::{de::DeserializeOwned, Serialize};

use super::{
    declaration::{Component, ComponentNode},
    NativeTool, Signal,
};

type ToolFuture = Pin<Box<dyn Future<Output = Result<ToolOutput, String>> + Send + 'static>>;

/// A mounted native tool that declares its latest two rounds of calls and results.
///
/// A round is one provider response containing calls to this mounted tool.
/// All calls in a round stay together, and pending rounds remain until completed.
/// Each round projects calls first, then results in the same call order.
/// Older records may remain in provider history until the port compacts it.
pub struct NativeToolCall;

impl NativeToolCall {
    /// Declare a typed callback, including callbacks that capture Component state.
    ///
    /// `view! { NativeToolCall { name: ..., description: ..., on_call: ... } }`
    /// uses these properties. `name` and `on_call` are required. A callback returns
    /// either `Result<Output, Error>` or a future producing that result. Use `||`
    /// for a tool without input fields; it accepts only an empty JSON object.
    pub fn props() -> NativeToolCallProps {
        NativeToolCallProps {
            name: (),
            description: "AgentView native tool".to_owned(),
            invoke: (),
        }
    }

    /// Mount a typed tool definition, including values generated by `#[tool]`.
    pub fn new<T: NativeTool>(tool: T) -> Component {
        let tool = Arc::new(tool);
        Self::props()
            .name(T::NAME)
            .description(T::DESCRIPTION)
            .on_call(move |arguments: T::Args| {
                let tool = Arc::clone(&tool);
                async move { tool.call(arguments).await }
            })
            .build()
    }

    pub fn named(name: &'static str) -> NativeToolCallNamed {
        NativeToolCallNamed { name }
    }
}

/// Properties for a native tool with a typed, state-capturing callback.
pub struct NativeToolCallProps<Name = (), Callback = ()> {
    name: Name,
    description: String,
    invoke: Callback,
}

/// A typed callback erased after its input schema has been derived.
#[doc(hidden)]
pub struct NativeToolCallback {
    schema: serde_json::Value,
    invoke: Box<dyn FnMut(ToolCall) -> ToolFuture + Send + 'static>,
}

impl<Name, Callback> NativeToolCallProps<Name, Callback> {
    pub fn name(self, name: &'static str) -> NativeToolCallProps<&'static str, Callback> {
        NativeToolCallProps {
            name,
            description: self.description,
            invoke: self.invoke,
        }
    }

    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }
}

impl<Name> NativeToolCallProps<Name> {
    /// Bind model-supplied arguments to a callback. Captured values are never
    /// included in the input schema. Expected business rejections should be
    /// serialized output values; returning `Err` reports a runtime handler fault.
    pub fn on_call<Arguments, Handler, Mode>(
        self,
        handler: Handler,
    ) -> NativeToolCallProps<Name, NativeToolCallback>
    where
        Handler: NativeToolHandler<Arguments, Mode>,
    {
        NativeToolCallProps {
            name: self.name,
            description: self.description,
            invoke: handler.into_native_tool_callback(),
        }
    }
}

/// Callback conversion for typed and zero-argument native tool closures.
#[doc(hidden)]
pub trait NativeToolHandler<Arguments, Mode>: Send + 'static {
    fn into_native_tool_callback(self) -> NativeToolCallback;
}

impl<Args, Handler, Return, Mode> NativeToolHandler<(Args,), Mode> for Handler
where
    Args: DeserializeOwned + JsonSchema + Send + 'static,
    Handler: FnMut(Args) -> Return + Send + 'static,
    Return: NativeToolCallbackReturn<Mode>,
{
    fn into_native_tool_callback(mut self) -> NativeToolCallback {
        NativeToolCallback {
            schema: schemars::schema_for!(Args).to_value(),
            invoke: Box::new(move |call| {
                let arguments = match serde_json::from_str::<Args>(call.raw_arguments()) {
                    Ok(arguments) => arguments,
                    Err(_) => return invalid_arguments(call),
                };
                native_tool_output(call, self(arguments))
            }),
        }
    }
}

impl<Handler, Return, Mode> NativeToolHandler<(), Mode> for Handler
where
    Handler: FnMut() -> Return + Send + 'static,
    Return: NativeToolCallbackReturn<Mode>,
{
    fn into_native_tool_callback(mut self) -> NativeToolCallback {
        NativeToolCallback {
            schema: serde_json::json!({
                "type": "object",
                "properties": {},
                "additionalProperties": false,
            }),
            invoke: Box::new(move |call| {
                let empty_object = serde_json::from_str::<serde_json::Value>(call.raw_arguments())
                    .is_ok_and(|input| input.as_object().is_some_and(|fields| fields.is_empty()));
                if !empty_object {
                    return invalid_arguments(call);
                }
                native_tool_output(call, self())
            }),
        }
    }
}

fn invalid_arguments(call: ToolCall) -> ToolFuture {
    Box::pin(async move {
        Ok(call.output(
            serde_json::json!({
                "error": {
                    "code": "invalid_arguments",
                    "message": "Arguments do not match this tool's input schema."
                }
            })
            .to_string(),
        ))
    })
}

fn native_tool_output<Return, Mode>(call: ToolCall, output: Return) -> ToolFuture
where
    Return: NativeToolCallbackReturn<Mode>,
{
    let future = output.into_tool_future();
    Box::pin(async move {
        let output = future.await.map_err(|error| error.to_string())?;
        let content = serde_json::to_string(&output).map_err(|error| error.to_string())?;
        Ok(call.output(content))
    })
}

impl NativeToolCallProps<&'static str, NativeToolCallback> {
    pub fn build(self) -> Component {
        Component::from_node(ComponentNode::NativeToolCall(Box::new(
            NativeToolCallDeclaration {
                name: self.name,
                definition: ToolDefinition::new(self.name, self.description, self.invoke.schema),
                history: None,
                round: Arc::new(()),
                invoke: self.invoke.invoke,
            },
        )))
    }
}

/// Conversion used by typed callbacks to accept synchronous and async results.
#[doc(hidden)]
pub trait NativeToolCallbackReturn<Mode>: Send + 'static {
    type Output: Serialize + Send + 'static;
    type Error: fmt::Display + Send + 'static;
    type Future: Future<Output = Result<Self::Output, Self::Error>> + Send + 'static;

    fn into_tool_future(self) -> Self::Future;
}

#[doc(hidden)]
pub enum SyncToolCallback {}
#[doc(hidden)]
pub enum AsyncToolCallback {}

impl<Output, Error> NativeToolCallbackReturn<SyncToolCallback> for Result<Output, Error>
where
    Output: Serialize + Send + 'static,
    Error: fmt::Display + Send + 'static,
{
    type Output = Output;
    type Error = Error;
    type Future = std::future::Ready<Self>;

    fn into_tool_future(self) -> Self::Future {
        std::future::ready(self)
    }
}

impl<HandlerFuture, Output, Error> NativeToolCallbackReturn<AsyncToolCallback> for HandlerFuture
where
    HandlerFuture: Future<Output = Result<Output, Error>> + Send + 'static,
    Output: Serialize + Send + 'static,
    Error: fmt::Display + Send + 'static,
{
    type Output = Output;
    type Error = Error;
    type Future = Self;

    fn into_tool_future(self) -> Self::Future {
        self
    }
}

pub struct NativeToolCallNamed {
    name: &'static str,
}

impl NativeToolCallNamed {
    pub fn on_call<Handler, HandlerFuture, Error>(self, mut handler: Handler) -> Component
    where
        Handler: FnMut(ToolCall) -> HandlerFuture + Send + 'static,
        HandlerFuture: Future<Output = Result<ToolOutput, Error>> + Send + 'static,
        Error: fmt::Display + Send + 'static,
    {
        Component::from_node(ComponentNode::NativeToolCall(Box::new(
            NativeToolCallDeclaration {
                name: self.name,
                definition: ToolDefinition::new(
                    self.name,
                    "AgentView native tool",
                    serde_json::json!({"type": "object", "additionalProperties": true}),
                ),
                history: None,
                round: Arc::new(()),
                invoke: Box::new(move |call| {
                    let future = handler(call);
                    Box::pin(async move { future.await.map_err(|error| error.to_string()) })
                        as ToolFuture
                }),
            },
        )))
    }
}

pub(crate) struct NativeToolCallDeclaration {
    name: &'static str,
    definition: Result<ToolDefinition, ToolDefinitionError>,
    history: Option<Signal<NativeToolHistory>>,
    // Render bindings serve one response; only dispatched calls retain this token.
    round: Arc<()>,
    invoke: Box<dyn FnMut(ToolCall) -> ToolFuture + Send + 'static>,
}

impl NativeToolCallDeclaration {
    pub(crate) fn name(&self) -> &'static str {
        self.name
    }

    pub(crate) fn definition(&self) -> Result<&ToolDefinition, &ToolDefinitionError> {
        self.definition.as_ref()
    }

    pub(crate) fn mount(&mut self, history: Signal<NativeToolHistory>) {
        self.history = Some(history);
    }

    pub(crate) fn append_call(
        &self,
        call: &ToolCall,
    ) -> Result<NativeToolRecord, NativeToolDispatchFault> {
        let history = self
            .history
            .as_ref()
            .expect("native tools are mounted before dispatch");
        let item = CanonicalInputItem::tool_call(call.call_id(), call.name(), call.raw_arguments())
            .expect("a ToolCall was already validated at admission");
        history
            .update(|history| {
                if history
                    .rounds
                    .iter()
                    .any(|round| round.call_ids.contains(call.call_id()))
                {
                    return Err(NativeToolDispatchFault::DuplicateCall {
                        call_id: call.call_id().to_owned(),
                    });
                }
                let round = match history
                    .rounds
                    .iter_mut()
                    .find(|round| Arc::ptr_eq(&round.identity, &self.round))
                {
                    Some(round) => round,
                    None => {
                        history.rounds.push_back(NativeToolRound {
                            identity: Arc::clone(&self.round),
                            calls: Vec::new(),
                            call_ids: HashSet::new(),
                            results: HashMap::new(),
                        });
                        history.rounds.back_mut().expect("just appended a round")
                    }
                };
                round.call_ids.insert(call.call_id().to_owned());
                round.calls.push(item);
                history.prune();
                Ok(())
            })
            .map_err(|error| NativeToolDispatchFault::History {
                message: error.to_string(),
            })??;
        Ok(NativeToolRecord {
            history: history.clone(),
            round: Arc::clone(&self.round),
            call_id: call.call_id().to_owned(),
        })
    }

    pub(crate) fn start(&mut self, call: ToolCall) -> Result<ToolFuture, NativeToolDispatchFault> {
        let call_id = call.call_id().to_owned();
        if call.name() != self.name {
            return Err(NativeToolDispatchFault::WrongTool {
                call_id,
                name: call.name().to_owned(),
            });
        }
        Ok((self.invoke)(call))
    }
}

pub(crate) async fn await_output(
    call_id: String,
    future: ToolFuture,
    record: NativeToolRecord,
) -> Result<ToolOutput, NativeToolDispatchFault> {
    match future.await {
        Ok(output) if output.call_id() == call_id => {
            record.append_result(output.content())?;
            Ok(output)
        }
        Ok(_) => Err(NativeToolDispatchFault::OutputCallIdMismatch { call_id }),
        Err(message) => Err(NativeToolDispatchFault::Handler { call_id, message }),
    }
}

#[derive(Default)]
pub(crate) struct NativeToolHistory {
    rounds: VecDeque<NativeToolRound>,
}

struct NativeToolRound {
    identity: Arc<()>,
    calls: Vec<CanonicalInputItem>,
    call_ids: HashSet<String>,
    results: HashMap<String, CanonicalInputItem>,
}

impl NativeToolHistory {
    pub(crate) fn items(&self) -> impl Iterator<Item = &CanonicalInputItem> {
        self.rounds.iter().flat_map(|round| {
            // Reset replays this projection directly, without ToolOutputStaging.
            round
                .calls
                .iter()
                .chain(round.calls.iter().filter_map(|call| {
                    let CanonicalInputItem::ToolCall { call_id, .. } = call else {
                        unreachable!("native tool rounds contain only admitted calls")
                    };
                    round.results.get(call_id)
                }))
        })
    }

    fn prune(&mut self) {
        let mut older_rounds = self.rounds.len().saturating_sub(2);
        self.rounds.retain(|round| {
            if older_rounds == 0 {
                return true;
            }
            older_rounds -= 1;
            round.calls.len() != round.results.len()
        });
    }
}

/// Pins a call to its original Component mount, including cancellation cleanup.
#[derive(Clone, Debug)]
pub(crate) struct NativeToolRecord {
    history: Signal<NativeToolHistory>,
    round: Arc<()>,
    call_id: String,
}

impl NativeToolRecord {
    fn append_result(&self, content: &str) -> Result<(), NativeToolDispatchFault> {
        let item = CanonicalInputItem::tool_result(&self.call_id, content)
            .expect("a native tool record retains a validated call identity");
        self.history
            .update(|history| {
                let Some(round) = history
                    .rounds
                    .iter_mut()
                    .find(|round| Arc::ptr_eq(&round.identity, &self.round))
                else {
                    // Only completed rounds can have left the retained window.
                    return Err(NativeToolDispatchFault::DuplicateResult {
                        call_id: self.call_id.clone(),
                    });
                };
                match round.results.entry(self.call_id.clone()) {
                    Entry::Occupied(_) => {
                        return Err(NativeToolDispatchFault::DuplicateResult {
                            call_id: self.call_id.clone(),
                        });
                    }
                    Entry::Vacant(result) => {
                        result.insert(item);
                    }
                }
                history.prune();
                Ok(())
            })
            .map_err(|error| NativeToolDispatchFault::History {
                message: error.to_string(),
            })?
    }

    pub(crate) fn finish_cancelled(&self, content: &str) {
        let completed = self
            .history
            .with(|history| {
                history
                    .rounds
                    .iter()
                    .find(|round| Arc::ptr_eq(&round.identity, &self.round))
                    .is_none_or(|round| round.results.contains_key(&self.call_id))
            })
            .expect("a cancelled reaction retains its Component mount");
        if !completed {
            self.append_result(content)
                .expect("cancellation closes each retained tool record once");
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub(crate) enum NativeToolDispatchFault {
    #[error("native tool history is unavailable: {message}")]
    History { message: String },
    #[error("tool call `{call_id}` is already recorded by this Component")]
    DuplicateCall { call_id: String },
    #[error("tool call `{call_id}` already has a result in this Component")]
    DuplicateResult { call_id: String },
    #[error("unsupported tool `{name}` for call `{call_id}`")]
    WrongTool { call_id: String, name: String },
    #[error("tool call `{call_id}` handler failed: {message}")]
    Handler { call_id: String, message: String },
    #[error("tool handler returned output for a different call than `{call_id}`")]
    OutputCallIdMismatch { call_id: String },
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::{identity::ComponentId, signal::SignalRuntime};

    fn declaration(history: &Signal<NativeToolHistory>) -> NativeToolCallDeclaration {
        let component = NativeToolCall::named("work")
            .on_call(|call| async move { Ok::<_, std::convert::Infallible>(call.output("done")) });
        let ComponentNode::NativeToolCall(mut declaration) = component.node else {
            unreachable!()
        };
        declaration.mount(history.clone());
        *declaration
    }

    fn call(call_id: &str) -> ToolCall {
        ToolCall::new(call_id, "work", "{}").unwrap()
    }

    #[test]
    fn old_pending_round_keeps_all_records_until_its_last_call_settles() {
        let runtime = SignalRuntime::new();
        let mut render = runtime.begin_render().unwrap();
        let history = render
            .render_component(ComponentId::root(), |scope| {
                scope.use_signal_at(0, NativeToolHistory::default)
            })
            .unwrap();
        render.commit();

        let first = declaration(&history);
        let completed = first.append_call(&call("first-completed")).unwrap();
        completed.append_result("done").unwrap();
        let pending = first.append_call(&call("first-pending")).unwrap();
        for call_id in ["second", "third"] {
            declaration(&history)
                .append_call(&call(call_id))
                .unwrap()
                .append_result("done")
                .unwrap();
        }
        let retained = history
            .with(|history| history.items().cloned().collect::<Vec<_>>())
            .unwrap();
        let expected = [
            CanonicalInputItem::tool_call("first-completed", "work", "{}").unwrap(),
            CanonicalInputItem::tool_call("first-pending", "work", "{}").unwrap(),
            CanonicalInputItem::tool_result("first-completed", "done").unwrap(),
            CanonicalInputItem::tool_call("second", "work", "{}").unwrap(),
            CanonicalInputItem::tool_result("second", "done").unwrap(),
            CanonicalInputItem::tool_call("third", "work", "{}").unwrap(),
            CanonicalInputItem::tool_result("third", "done").unwrap(),
        ];
        assert_eq!(retained, expected);

        pending.finish_cancelled("cancelled");
        completed.finish_cancelled("cancelled");
        pending.finish_cancelled("cancelled");
        assert_eq!(
            history
                .with(|history| history.items().cloned().collect::<Vec<_>>())
                .unwrap(),
            expected[3..],
            "the closed old round leaves as a whole, and cleanup remains idempotent"
        );
    }
}
